name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message:
            This issue has been automatically marked as stale because it hasn't had any activity in 60 days. 
            It will be closed in 7 days if no further activity occurs
            (e.g. changing labels, comments, commits, etc.). Please feel free to
            tag a maintainer and ask them to remove the label if you think it doesn't apply.
            Thank you for submitting this issue and helping to make Google Data Catalog Connectors better!
        stale-pr-message:
            This PR has been automatically marked as stale because it hasn't had any
            activity in 60 days. It will be closed in 7 days if no further activity occurs
            (e.g. changing labels, comments, commits, etc.). Please feel free to
            tag a maintainer and ask them to remove the label if you think it doesn't apply.
            Thank you for submitting this PR and helping to make Google Data Catalog Connectors better!
        stale-issue-label: 'no-issue-activity'
        stale-pr-label: 'no-pr-activity'
